#ifndef foominidumphfoo
#define foominidumphfoo

#include <sys/types.h>
#include <stdio.h>

/* Terms:
 *
 * coredump: an ELF coredump as generated by the kernel
 * minicore: an reduced size ELF coredump, augmented with userspace data
 * minidump: a Windows/Breakpad compatible minidump
 *
 * We can convert:
 *
 * A running process            → minidump
 * A running process            → minicore
 * A coredump                   → minidump
 * A coredump                   → minicore
 * A coredump + running process → minidump
 * A coredump + running process → minicore
 * A minidump                   → minicore
 *
 * A minicore may be used as input wherever a coredump is expected.
 */

/* You may set either pid = 0 or coredump_fd = -1 */
int minidump_make(pid_t pid, int coredump_fd, void **minidump, size_t *size);

/* You may set either pid = 0 or coredump_fd = -1 */
int minicore_make(pid_t pid, int coredump_fd, void **minicore, size_t *size);

int minidump_show(FILE *f, int minidump_fd);

/* You may set either pid = 0 or coredump_fd = -1 */
int coredump_show(FILE *f, pid_t pid, int coredump_fd);

int minidump_to_minicore(int minidump_fd, void **minicore, size_t *size);

#endif
